import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { PlugZap, ShieldCheck, RefreshCw } from "lucide-react";
import { api, errorMessage, unwrap } from "../../api";
import { Button, Card, ErrorState, PageHeader, Section, Badge } from "../../components/ui";
interface Integration { type:"HRIS"|"LMS"; name:string; baseUrl:string; status:string; lastSyncAt?:string }
interface SsoProvider { name:string; type:"OIDC"|"SAML"; enabled:boolean; issuerUrl?:string; clientId?:string; authorizationUrl?:string; tokenUrl?:string; userInfoUrl?:string; entryPoint?:string; idpCert?:string; entityId?:string; allowedDomains?:string[] }
export default function IntegrationsPage(){
 const qc=useQueryClient(); const [type,setType]=useState<"HRIS"|"LMS">("HRIS"); const [name,setName]=useState(""); const [baseUrl,setBaseUrl]=useState(""); const [apiKey,setApiKey]=useState(""); const [ssoType,setSsoType]=useState<"OIDC"|"SAML">("OIDC"); const [sso,setSso]=useState({name:"Corporate SSO",issuerUrl:"",clientId:"",clientSecret:"",authorizationUrl:"",tokenUrl:"",userInfoUrl:"",entryPoint:"",idpCert:"",entityId:"",allowedDomains:""});
 const iq=useQuery({queryKey:["integrations"],queryFn:async()=>unwrap<Integration[]>(await api.get("/infrastructure/integrations"))}); const sq=useQuery({queryKey:["sso-provider"],queryFn:async()=>unwrap<SsoProvider|null>(await api.get("/infrastructure/sso/provider"))});
 const save=useMutation({mutationFn:async()=>unwrap(await api.put("/infrastructure/integrations",{type,name,baseUrl,apiKey})),onSuccess:()=>{qc.invalidateQueries({queryKey:["integrations"]});setApiKey("")}});
 const saveSso=useMutation({mutationFn:async()=>unwrap(await api.put("/infrastructure/sso/provider",{...sso,type:ssoType,enabled:true,allowedDomains:sso.allowedDomains.split(",").map(x=>x.trim()).filter(Boolean)})),onSuccess:()=>qc.invalidateQueries({queryKey:["sso-provider"]})});
 async function test(t:string){try{await api.post(`/infrastructure/integrations/${t}/test`);qc.invalidateQueries({queryKey:["integrations"]})}catch(e){alert(errorMessage(e))}} async function sync(t:string){try{await api.post(`/infrastructure/integrations/${t}/sync`);qc.invalidateQueries({queryKey:["integrations"]})}catch(e){alert(errorMessage(e))}}
 if(iq.isError||sq.isError)return <ErrorState text={errorMessage(iq.error||sq.error,"Unable to load integrations.")}/>;
 return <div className="space-y-6"><PageHeader eyebrow="Organization administration" title="Integrations & SSO" description="Connect identity, HRIS and LMS systems for your organization."/>
 <Card><Section title="Single sign-on" description="Configure OIDC or SAML for organization-wide authentication."><div className="grid gap-4 md:grid-cols-2"><label><span className="label">Protocol</span><select className="field" value={ssoType} onChange={e=>setSsoType(e.target.value as any)}><option>OIDC</option><option>SAML</option></select></label><label><span className="label">Provider name</span><input className="field" value={sso.name} onChange={e=>setSso({...sso,name:e.target.value})}/></label><label><span className="label">Issuer URL</span><input className="field" value={sso.issuerUrl} onChange={e=>setSso({...sso,issuerUrl:e.target.value})}/></label><label><span className="label">Client ID</span><input className="field" value={sso.clientId} onChange={e=>setSso({...sso,clientId:e.target.value})}/></label>{ssoType==="OIDC"?<><label><span className="label">Client secret</span><input className="field" type="password" value={sso.clientSecret} onChange={e=>setSso({...sso,clientSecret:e.target.value})}/></label><label><span className="label">Authorization URL</span><input className="field" value={sso.authorizationUrl} onChange={e=>setSso({...sso,authorizationUrl:e.target.value})}/></label><label><span className="label">Token URL</span><input className="field" value={sso.tokenUrl} onChange={e=>setSso({...sso,tokenUrl:e.target.value})}/></label><label><span className="label">User info URL</span><input className="field" value={sso.userInfoUrl} onChange={e=>setSso({...sso,userInfoUrl:e.target.value})}/></label></>:<><label><span className="label">SAML entry point</span><input className="field" value={sso.entryPoint} onChange={e=>setSso({...sso,entryPoint:e.target.value})}/></label><label><span className="label">Entity ID</span><input className="field" value={sso.entityId} onChange={e=>setSso({...sso,entityId:e.target.value})}/></label><label className="md:col-span-2"><span className="label">IdP certificate</span><textarea className="field min-h-24" value={sso.idpCert} onChange={e=>setSso({...sso,idpCert:e.target.value})}/></label></>}<label className="md:col-span-2"><span className="label">Allowed email domains</span><input className="field" value={sso.allowedDomains} onChange={e=>setSso({...sso,allowedDomains:e.target.value})} placeholder="company.com, subsidiary.com"/></label></div><div className="mt-4 flex items-center gap-3"><Button onClick={()=>saveSso.mutate()} loading={saveSso.isPending}><ShieldCheck size={15}/> Save SSO configuration</Button>{sq.data&&<Badge tone={sq.data.enabled?"green":"slate"}>{sq.data.enabled?"Enabled":"Disabled"}</Badge>}</div><p className="mt-3 text-xs text-slate-600">OIDC callback: /api/auth/sso/oidc/callback · SAML callback: /api/auth/sso/saml/callback</p></Section></Card>
 <Card><Section title="HRIS / LMS"><div className="grid gap-4 md:grid-cols-2"><label><span className="label">Type</span><select className="field" value={type} onChange={e=>setType(e.target.value as any)}><option>HRIS</option><option>LMS</option></select></label><label><span className="label">Name</span><input className="field" value={name} onChange={e=>setName(e.target.value)} placeholder="Workday / Moodle"/></label><label><span className="label">Base URL</span><input className="field" value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} placeholder="https://api.example.com"/></label><label><span className="label">API key</span><input className="field" type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="Secret key"/></label></div><div className="mt-4"><Button onClick={()=>save.mutate()} loading={save.isPending}>Save integration</Button></div></Section></Card>
 <Section title="Connected systems"><div className="space-y-3">{(iq.data||[]).map(i=><Card key={i.type} padding="sm"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><PlugZap size={18} className="text-brand-300"/><div><p className="font-semibold text-white">{i.name}</p><p className="text-xs text-slate-600">{i.baseUrl}</p></div><Badge tone={i.status==="CONNECTED"?"green":i.status==="ERROR"?"red":"slate"}>{i.status}</Badge></div><div className="flex gap-2"><Button variant="secondary" onClick={()=>test(i.type)}>Test</Button><Button variant="ghost" onClick={()=>sync(i.type)}><RefreshCw size={14}/> Sync</Button></div></div></Card>)}</div></Section></div>
}
